apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 15m
  timeout: 10m
  targetNamespace: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1h
      version: 1.19.5
  values:
    allowLoopDevices: true
    useOperatorHostNetwork: true
    enableDiscoveryDaemon: true
    logLevel: INFO
    csi:
      enableCSIHostNetwork: true
      csiAddons:
        enabled: false
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi
