apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dolt
resources:
  - namespace.yaml
  - storage.yaml
  - statefulset.yaml
  - services.yaml
  - networkpolicy.yaml
  - auth.sops.yaml
configMapGenerator:
  - name: dolt-init
    files:
      - init.sql
