apiVersion: ENC[AES256_GCM,data:3v4=,iv:OMn1rpyv8CHLRCPkOXRwBJorAsMFomsrfY3d9hOBhpM=,tag:4nafntSMg4SY457jAjT0eQ==,type:str]
kind: ENC[AES256_GCM,data:gX3hhY0j,iv:/JiaYV5X6xsH2I9UiXawjtArbkL0BU7ZAaarIJfYfqY=,tag:VAuQ0ZLCXwwlwDrYvDYmlA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:goDODcMajnCIQw==,iv:1TJhAwAPvlbfvodtra8J+HO0kRrRRxFIhgSKYna2TJA=,tag:OCXPpPikuTP3GCPgVw15iA==,type:str]
    namespace: ENC[AES256_GCM,data:crKtC1KtMvkVhw==,iv:viSgbIL3gtqwX282gfWhEIr+/2c2JTC5uRsLMiZUgCk=,tag:hieVAoMzpibQ56pdDCBzAg==,type:str]
data:
    PERMIT_API_KEY: ENC[AES256_GCM,data:VumydxOn9dh5TzTOtfmyrAsYN32hqo/9WnDFnxXJ0+gW8nD7PEe5/gwL/kuWk2ZPO9lQ1cVddF3mlWbOkYMfzK1NItKhrTOxugrECsyE8QhKSRG27wisJidylghSGOrPKtYS43DsZRG8SX1fmD5t3qSEA8F8nvAiUwsPefJtkcVu5b7I,iv:mcs/g/xSzznZwpdgI/JbZrGP5Kp5E2RSIRGxjmGUDRw=,tag:mHmG2glqkOiAvDqMK04T8Q==,type:str]
sops:
    age:
        - recipient: age105q796d973wvg0p3t4m0yfdqwzpztvvhj6v9gyllfywd3cdcvd5q9vwu2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRUgwUHJKS1ZjMnk3eFdI
            R2kvaVFzNExwSkw1NHZrS2cvQXZRdTh1dkVnCnpGZlJ1ekphKzlCSzA3bkdaNFE4
            a3RXemxhbDl5a3QxRUgrQ3FRRWZJalUKLS0tIDBQRzlOVnJqeVpoSHhRZ1VpYjRu
            RC9GRmgrUm5iREwvK0ZKcDhwQWYwbG8K78GeqGzvr+hMEpLEKs/bVUgwOELwnjpQ
            yrRdIrb+Py3uo+53AGCx+7Aa9UrnInn9cIsiy8BKITkmKa8tFa4QEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T02:23:12Z"
    mac: ENC[AES256_GCM,data:rcV+WkkYN+idoyiKoNRZw/9QvqKPKn5oBwbvLsl2Jr25lmNgyHwyx+7hSPuMEw9buV4Nvj3zbzm8+Srk6x1JePIxuNCXYpW2ZUYMwdO/VDjKTwpe/TUM2lQbgVYYLG3ViH6JnXEnYQC3Yv0O5YyCQKg+bQB/1tWO6nRgQgnKlII=,iv:G/ituc8dI4eepgHc6LorZ9jpgVbGdWNbNYawui53T5Q=,tag:SH1eV9lzSEK4KIG1aeIQ5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
