apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: homeharbor
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:VRKyXxDNukR7ls7930DNuIm5QLZREKGGMqcM8PAIb1mImhERFrM0ZRipvbd99bSATmpDrts=,iv:pEZTNi2oidecLEbhETANGAGNxQzd8BRwOrbxbZta1cU=,tag:OkWPGA8jeSKWy3gBVHLSWA==,type:str]
sops:
    age:
        - recipient: age105q796d973wvg0p3t4m0yfdqwzpztvvhj6v9gyllfywd3cdcvd5q9vwu2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V1ZKK3RiWjV6a1c3U0Nw
            aHFna3hBVUo5b25BUkZhQzJPNmljZXVVMlVrCnNRV3NzK1hPZTJMaCtSUlBVN3Bm
            TC9VeFFuN2kvSDl0K2RHYk12ajR5VmMKLS0tIHc4L1hZTlk4RHhVeFVLcSsrNEZx
            L0tKWjYwSnlhQkpuNWlZUGJneFpUcVEKAhmmV0sBdvbVIg5Y1f30btDsRugE2xlr
            P4qU7DfbDjtd667S/zFMhKDZ4LuD/oIL3hBtoJcohcZwjWsyIARAjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T13:28:54Z"
    mac: ENC[AES256_GCM,data:gkIGEQFpUvLLTuPiU+vpQsvOpnEFqnDw2w/pwmP3UeHPjThIpDReU6UIOw7xGdz5Qn1bdm9v98ArmIAs4bRXXkJXDf5F+5w1JwdoXZXu5YAiRRLWocMWLAXhODVykTcxvtzNSyR0bi9ApsWijm4pAr5Y9WXR7EIq5LfOCHh8hTo=,iv:Q2ritOHAEciyBQBB28gxHg2s/JVKk7x6D5nU+OAXtQM=,tag:/Wlw6C/tPnj/JK9pH/WNaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
