apiVersion: v1
kind: Secret
metadata:
    name: homeharbor-values-secrets
    namespace: homeharbor
stringData:
    values.yaml: ENC[AES256_GCM,data:4NfdyfjvHJmlwd9ZyPIgd8Ejd10JQ9FKvHAdjat84t7FVNPtgGowvcEhEtYKYH8CjFBwrzS9bbFND/bhPG4OS3BcZvTfViuSyw1AdolIJiE/UWgJP30Bl27ge8OhAhpTW0TSNpUssSRoMhVdATjh6IP+Awt7a33/LaZSgZ3r6ZX8QsgaUjsEky5fl5abReEmyc4uhwfP+iDfDpX4caf7DiaMEkvlH2PfmlqK/SRf/9kKrnbTebHEH3OJsSTCc9nEL1ya2UdKLI90kfllSjZmIRGgR0gTU1iu7IUxcFHplU1qORxu+hy8e4fsXiE9UbRGy2CUlV931L80plpAp3HKhAd1G8mA+qzIzce89N0k13UwvtvocYyqmNhKOecC05cmYdULXsF8E7L2HLIWcCJw12EjRyCLNDIIRB1MP0IqNUr2v/epbbf2rbBlOD28tJXpJtF3zveQhxjzbsL5iH73v2vIBNFHBwnAcA7/sF1LdS7wnPV4Lbi8Fi6T/Ttz8aG12P9cgxHE7+IGnp9ywSEB+69cLOb0LkhV1EiZnS2ycW014+wykSZivDTJe0b25X1qN/Ov6NMwKXeb9MtPEmhovexhx1/2c8jSqemHeFZyYGXL54CqizUfE43wudeL6xGQnuKduvKctPB2at2hE05RocOI8/WTIacspf7eD45tGR6dC5R2NSYc00r07kKpjjZdmtFqrPv3gZTkXKWOYOGkP3jy+6uCqBYX6MUS17bZ0mWyEOzoaiFeVzadgHriLX68tYAXfaYtrUvw7y0f+UzzuKYckqjbjO15Xt+5wVG1bbP+dNORii/xOMTctBnJoIHSWEsc6ZoI9cjdPhV3nFU5Qd8dTVRacRh2eQTsny+gfKre3R6e6V01eZBox2Y0ztcF7w==,iv:/arORdouPaGBeZ2TV0Mk87DwDliuSw5Qtzc+spY1KAk=,tag:TR3JcRbHPckbpuc8wVXAGg==,type:str]
sops:
    age:
        - recipient: age105q796d973wvg0p3t4m0yfdqwzpztvvhj6v9gyllfywd3cdcvd5q9vwu2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWlIvaHgrY092Y3F4MHJ3
            dzB1QmpJSVZsTXhmUHE2emVCakduQVpLRGdnCnpmT0RiTFdSbkNXKzU0RC85Q3hN
            VmxKRVlXdHl6YVhYMEh3dHV6QzlacnMKLS0tIHd1bG9VYS9Td1dseElzOCs2cWtl
            aUJPa1R2MWFrZ0N5MlFYc3FtUXQ2eEUK7R3dMO0IlXNSEPEeG7z59lRCMYShGEo7
            MkLd/7ud6TMyPgmrXT52XuS5dsRmgU4b84Bl9zh7EdL4V1noRxuXMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T05:03:43Z"
    mac: ENC[AES256_GCM,data:sJ5cRnygLyhjRKvLTtNdR0I6aN7FYxpHNXLl3curFh1YN/PexLIoaMlxLxp7kLWGfMlY1yeS898DPsT7olJVy/55oKar4JmiFkRPuma6dgraJvokcmdN7F0f7Rqk2lkedfVtjM4qINhzCV8OHRSb9asULWEuCTs1WL3lR+jj8bc=,iv:KBFlyTSAdxQnLLnhD9Wz3p2LVUUp5TYynKYOFYMPi2o=,tag:HEVSwpl+tnWOU7X6srvNUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
