image:
  api:
    repository: ghcr.io/zjpiazza/homeharbor/api
    tag: latest
  worker:
    repository: ghcr.io/zjpiazza/homeharbor/worker
    tag: latest

domain: homeharbor.cloud
apiHost: api.homeharbor.cloud

cloudflare:
  accountId: "5cb5a4fcfcdb8d4f4e01283f2c3eedbc"
  email: "zjpiazza@gmail.com"

database:
  size: 5Gi
  instances: 1

storage:
  bucketName: homeharbor-storage
