apiVersion: ENC[AES256_GCM,data:uGA=,iv:6IY/se01kKlVGc299bNudnzNp4/97GlA6D+W897us3E=,tag:rhDwuHZqz2yB6BShos6a1A==,type:str]
kind: ENC[AES256_GCM,data:1fvpKP9J,iv:8dcinRzeddEjkGQp/7InI5Cdz21WYt0wpZtnmeV4CXo=,tag:RPY8rBXqozS5/AAqUXJk9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jQkAQAb5Np9raqkI470HJu3rEw6mPGCYUQ==,iv:5Y/wuJUJmk4pyu91TOdOiuUjCFf/AksccUWzhRRzpbE=,tag:1mYbU49xGNxDSLd5HgKU/w==,type:str]
    namespace: ENC[AES256_GCM,data:hnti4OzYzRNaXQ==,iv:KdbKSX3tdous73n2f9okQz2HpT47mrMKZSisx53dJrA=,tag:40lF2nqRZ1lJU1uk33C9yQ==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:4c4Y1VaBQLE8A7YFozmAxbecsOPYIu5bb3AnpconTJaO+cAh+NKsZzH2MZsUxlCxqqSUKlIpyTazuzeEfRfZVkbUjZlUlEBij8INwDmrr7nWOd6NntLJOLqBFL7KEakaMQeOnM+Jj1mMiXZy/9kDsbvVBflS3KmzP1ux5E35cnw7Hf9CatBZ+xn5glS0UPkc/kZ47ILhnookgMjR2iMjcBn0CDNmwM0hRySmi/NrfkYo1yfb2armb8ABHeDFP0hYFveGGr7XvkYeOAhpDnBRF+ECz8k1ygWMclbZcBD6DSPdcGUhpSh9Z61kQfXP4BZbH8DECZYMR9yw4CGLTR2EMRfjt3wnmFzkmLyADagVG7zMwfeMcNeZ2rOk4K/wEnrEQiCMj/USv6l88xYLl3MW+0N7wMXBsPmKLZCLEN/TdgIMRpv3YrU8WhujT8dkLwVg+fTCUQz8F91x0DT5Q6xdCo0TZUiGUKWP6ej5IRHo8jAOTRMnwUUZGBmTRxgVI7C/erhcIMvKfQOTDTHf82nkrcmRXE/GDuvJ80JiV35696iBzQ2X4fbP1iHrfPRNySD8DmMsBMIVDS26FixOZwsw8viwkEtpZiVqKm23skUQzFs5Hp1c7MJdU3uPuffyyCWJaeLE+31Lq0KmR2ec7z3j22YytBfJXelWXbi918opA+VqVlDC9xFvkOHt6bTQfjOvb6OpV3SI6qLrDA6F3vn9RsAK/mo8d5qDDNxj/Nz956zjDhoT7VV4/R0oaWNP/U2MFxUCj55mK1xwtbiNQcKdwnd8I3Dde366gukS02N3gnouzGDHCCtAeh0mwI/7woYpEOEofoSLR4bM15qv9pUreKzI3HoxyM6kB++vmSAWqJJyWVU1mYQ1QAmyAuAHDpnyew==,iv:gh1lgrhqwRLxSVviBKJIe+vWo8ymQ73tWOWaTZhDWzE=,tag:sS/RnOo/HA4jwEYZ8e1oEg==,type:str]
sops:
    age:
        - recipient: age105q796d973wvg0p3t4m0yfdqwzpztvvhj6v9gyllfywd3cdcvd5q9vwu2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMDdDUmV2R1hnUmlkNmtS
            akdqbEk5WVk2Rk1vSmY3UzNDM2hjR1FkOHhjCk1EMzBraDd3YlFqckYzQkFuVms0
            NjVRN3ZaQU83SGJSbzg0R0NpSWgram8KLS0tIHQ0RStnM21nZWEwUzhIM2dWeExE
            VllWZ0hoZlZ0bEVNWnNacHlOcTVLOGcKVFy/scTvHPzUEPbRjq5RLA0LZB+KJGC/
            J/C5r6RUPle+/nTxYzphzTDzsjLSzSQdzj4XEjE7XUINtF9Zq+v8XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T02:15:17Z"
    mac: ENC[AES256_GCM,data:Zh6ZvKaO442+y5W7wPykVz0GHokk0cyDT47+l2Vcgd/2TfhMbL3fY9huMhRKhIC5s7UFJeZao8+R/OuhJkgxx2qCWirO9OrIQUz2bzc5OyykAZ3gOm41J1vIMgNIqC6nQeDA/FViy3YJoJ+BgtiQyqK/YxS6ttG5FJyOJfN/4Q8=,iv:+GE6hOFZSvoi81bh2NwIpBRxHFmGCyDaCs8FeRWHXuQ=,tag:ZqQEQil8v4kXv07LnAFV6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
