# dnsmasq config: PXE proxy + TFTP
port=0
dhcp-range=192.168.1.0,proxy,255.255.255.0
dhcp-no-override
log-dhcp
enable-tftp
tftp-root=/srv/tftp
dhcp-boot=ipxe.efi,192.168.1.229
pxe-service=7,"Talos PXE",ipxe.efi,192.168.1.229
pxe-service=0,"Talos PXE",ipxe.efi,192.168.1.229
