apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - inngest-pg-cluster.yaml
  - inngest-secret.sops.yaml
  - inngest-deployment.yaml
  - inngest-service.yaml
