apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: affine
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  path: ./apps/envs/prod/affine
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
