apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- flux-image-automation-kustomization.yaml
- permit-pdp-kustomization.yaml
- inngest-kustomization.yaml
- homeharbor-kustomization.yaml
- affine-kustomization.yaml
