apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: permit-pdp
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  path: ./infrastructure/controllers/permit-pdp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      namespace: flux-system
