apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:6F/1Io5hoX4+8vnb3rP0IYAqcnUXkJYQ4ubaoKdu+hmyKf+ceWenJ+C2ZqWfZCbyM8OSknE=,iv:NxumF59ImCXbc1cAJr4I9k0s+XC4OS7SRran96XWA/U=,tag:aevIWzVayP1spiKf35b1wQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Wm9HS0pnOUVCNE9Qb29C
            T2I3U2Q4V3d3RzFhQVNkWVluam1ZRFNCcjA4CndhTDV1eFVrY0tUWjM3aENyWHRa
            VnNGSlpzbHBiYkxGMjNHcHdiUTlqQ2sKLS0tIHZnaWp6MGtpRHExdk54eXdodFdG
            Mnh6YzVJRXV3b2VtUWhKM2gycUlSbVkK3pCLY7m9B8w2yQI1dXIYtEVSh4CYfNrm
            bRSSmntgAL2QLscvZK7qDtW8AkdbjYOd+TlPUaVbTc+JuMMd+aCvIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age105q796d973wvg0p3t4m0yfdqwzpztvvhj6v9gyllfywd3cdcvd5q9vwu2n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T13:27:24Z"
    mac: ENC[AES256_GCM,data:WXGN7OF78hlPWZNWyQRXCzBQ4+twZT898LB0pelWHa+iKnj23qR5oQ/msxK/QQvGJOfo4CcgNMB7qUSPLpKMMzJKQ+ISGtUAs58thu40WFsrlXyFR4SKsZyE/7M//8FRdhxH+IkiRZyQavy+fyVLqyTkUUNJEF6Ah30sGzB7pDA=,iv:xPcVr2qUfPVhWBpEVAjfN+uU6Vxx0kAOB/9AvCovRv4=,tag:X7FJhv/+eQXDefuiCNWccQ==,type:str]
    version: 3.13.1
