apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:IguiKhcnmeA3ZM6zR2ucofh0AkU3ZW7U23q96mUC4LO2ishqVIbmZq+GSH/KuvJ/ppM/BDE=,iv:7F7yCNEj7wSJO1VZbcUEK2GpLj8/FUGV/Q+3ief9g1I=,tag:MrKzysiI+qLLRDPM54NbQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDN2tyYmJzNzJURFhTUkE5
            MWU4eU9mUDNSYUEwSHluWjliWm5zMEhNdkVBClZEZllnd0tMSDFtdXZMY2tWVktT
            REJxUjEzSlpkdy9uVWNuUFZ4aWpQcXMKLS0tIDRLQXZXR0lQRXBJOStvOUVLNEw3
            MXdnL1JRbWh6QzVwaHhYNkZ0cE0rSDgKgkkX3vBliOqhdvPzqJVI3/XkjgTavmpt
            yrDeGErAk0B/JOomOnYY6R+6qT1YLutUWr8j/Hd4dLpnTY9Zf5B/ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swfkes9cealehclknyt350m8lj7faw3xwvnx3mllr28xeekq3vyqe8545h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T21:59:57Z"
    mac: ENC[AES256_GCM,data:t2JKXNQp4lqFVFsuxJYt9rnsB88xdGFrDteTUVlerRB8xRwqM2UaoLZUERpBZ6iRE9Mnl+cf2QMfAA77IeS5R6sQzYYGJE3HdDiA6TUtsS1Ui+kqO8QK4hZsZDFpr/xvu2avXnUF+MA0WODKbTTkM8mZ5ZJII9evwa6A+7JgGTc=,iv:9xPr3EePuqhQ5BPlrZYWXAvE0KYeng29+9161ehc9aA=,tag:4jwon5xl6WBm/QCbaRtpew==,type:str]
    version: 3.13.0
