apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:9qrrxmO6W08PdVlCnnPILOLrS9WYrZiy/XktATGx5pbJZeAxNT1LBdjowPfQkSliBHuOMKU=,iv:3xR7mx2EWYorib9dkjowyl5RLqgFOaGcHtagKkO+hTg=,tag:i0d3X1EEUTMCKrviCdGHyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Wm9HS0pnOUVCNE9Qb29C
            T2I3U2Q4V3d3RzFhQVNkWVluam1ZRFNCcjA4CndhTDV1eFVrY0tUWjM3aENyWHRa
            VnNGSlpzbHBiYkxGMjNHcHdiUTlqQ2sKLS0tIHZnaWp6MGtpRHExdk54eXdodFdG
            Mnh6YzVJRXV3b2VtUWhKM2gycUlSbVkK3pCLY7m9B8w2yQI1dXIYtEVSh4CYfNrm
            bRSSmntgAL2QLscvZK7qDtW8AkdbjYOd+TlPUaVbTc+JuMMd+aCvIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age105q796d973wvg0p3t4m0yfdqwzpztvvhj6v9gyllfywd3cdcvd5q9vwu2n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T14:31:57Z"
    mac: ENC[AES256_GCM,data:sorzjbZ/jZbtOeyl1LIx6SILk6Gr5u9P67ROEFBK/UkYDXbsaM5GBBrYQcixRXJUf93XshSN+E1HYCWhULU6uXF9lSWmE5NrloAjV7AuD0JEdXLteoPyGj6dZkPfsKPvu4NZCBpsbjMdogVV1OYxqtIQelzagCfpmZlFSI2c8ig=,iv:Psy4j/SCTMixCzEj2GQW6r+R6cideQGCEkGtve/oYaY=,tag:YJxYCkQA914pQcVvH3+vKQ==,type:str]
    version: 3.13.1
