apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: homeharbor
  namespace: homeharbor
spec:
  interval: 5m
  url: oci://ghcr.io/zjpiazza/charts/homeharbor
  ref:
    semver: "*"
